using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

public class HierarchyItem : MonoBehaviour
{
    public LayoutElement parentLayoutElement;
    public RectTransform rectTransform;

    public Button expandButton;

    public Button editnameButton;
    public Toggle toggle;
    public TextMeshProUGUI text;
    public TMP_InputField nameInput;
    public GameObject boundObject;
    public Transform verticalLayoutGroup;
    public int childCount = 0;
    public int actualChildCount = 0;
    public bool showChildren = true;

    public Color normalColor_on;
    public Color normalColor_off;
    public Color noChildColor;



    void Awake()
    {
        editnameButton.gameObject.SetActive(false);
        nameInput.gameObject.SetActive(false);
        toggle.onValueChanged.AddListener(isOn =>
        {
            if (isOn)
            {
                //‰øÆÊîπnormal color‰∏∫ÁÅ∞Ëâ≤
                toggle.GetComponent<Image>().color = normalColor_on;
                editnameButton.gameObject.SetActive(true);

                // verticalLayoutGroup.GetComponentsInChildren<HierarchyItem>(true).ToList().ForEach(item =>
                // {
                //     item.toggle.isOn = true;
                // });
            }
            else
            {
                //‰øÆÊîπnormal color‰∏∫ÁôΩËâ≤
                toggle.GetComponent<Image>().color = normalColor_off;
                editnameButton.gameObject.SetActive(false);
                // verticalLayoutGroup.GetComponentsInChildren<HierarchyItem>(true).ToList().ForEach(item =>
                // {
                //     item.toggle.isOn = false;
                // });
            }
        });

        // ÁÇπÂáªÁºñËæëÊåâÈíÆÔºåÊòæÁ§∫ËæìÂÖ•Ê°ÜÂπ∂ËµãÂÄºÂΩìÂâçÂêçÂ≠ó
        editnameButton.onClick.AddListener(() =>
        {
            nameInput.text = text.text;
            nameInput.gameObject.SetActive(true);
            nameInput.Select(); // ËÅöÁÑ¶
        });

        // ÂΩìÁî®Êà∑Êåâ‰∏ã Enter ÊàñÂ§±ÂéªÁÑ¶ÁÇπÊó∂Êèê‰∫§
        nameInput.onEndEdit.AddListener(newName =>
        {
            if (!string.IsNullOrWhiteSpace(newName))
            {
                text.text = newName;
                gameObject.name = newName; // Êõ¥Êñ∞ root.name
                if (boundObject != null)
                {
                    boundObject.name = newName; // üëà Êõ¥Êñ∞ÂØπÂ∫î GameObject ÁöÑÂêçÁß∞
                }

            }
            nameInput.gameObject.SetActive(false);
        });
    }

    void Update()
    {
        Expand();
        ChangeToggleSprite();
    }

    public void Expand()
    {
        childCount = showChildren ? GetComponentsInChildren<HierarchyItem>(true).Where(x => x.gameObject != gameObject).Count() : 0;
        actualChildCount = GetComponentsInChildren<HierarchyItem>(true).Where(x => x.gameObject != gameObject).Count();
        verticalLayoutGroup.gameObject.SetActive(showChildren);
        parentLayoutElement.preferredHeight = 50 + 50 * childCount;
        rectTransform.localPosition = new Vector3
        (
            rectTransform.localPosition.x,
            (parentLayoutElement.preferredHeight - 50) / 2,
            rectTransform.localPosition.z
        );
    }

    public void ChangeToggleSprite()
    {
        if (actualChildCount == 0)
        {
            expandButton.GetComponent<Image>().color = noChildColor;
        }
        else
        {
            expandButton.GetComponent<Image>().color = normalColor_on;
            if (showChildren)
            {
                expandButton.GetComponent<Image>().sprite = HierarchyUI.Instance.expandSprite;

            }
            else
            {
                expandButton.GetComponent<Image>().sprite = HierarchyUI.Instance.collapseSprite;

            }
        }


    }

}
